#!/bin/bash

$platform = $(uname -ms)

function info() {
    echo -e "\e[1;97minfo:\033[0m $1"
}
function warn() {
    echo -e "\e[1;93minfo:\033[0m $1"
}
function err() {
    echo -e "\e[1;93minfo:\033[0m $1"
}

info "Initiating installation"

if [[ -d "~/.catalyst" ]]; then

    read -n1 -p "Catalyst already installed. Reainstall it?" REINSTALL

    if [[ $REINSTALL == "y" ]]; then
        info "Reinstalling"
        rm -rf ~/.catalyst
    else
        info "Exiting"
        exit 0
    fi

fi

info "Checking system"

case $platform in
'Linux aarch64' | 'Linux arm64')
    target=linux-aarch64
    ;;
'MINGW64'*)
    target=windows-x64
    ;;
'Linux x86_64' | *)
    target=linux-x64
    ;;
esac

info "Downloading binary"

curl -sSL --progress-bar https://github.com/tunafysh/Catalyst/releases/download/v0.0.2/catalyst-linux-amd64.tar.gz | tar -xzv -C ~/.catalyst/bin catalyst
