#!/bin/bash

$platform = $(uname -ms)

function info() {
    echo -e "\e[1;97minfo:\033[0m $1"
}

function warn() {
    echo -e "\e[1;93mwarning:\033[0m $1"
}

function err() {
    echo -e "\e[1;93merror:\033[0m $1"
}

info "Initiating installation"

if [[ -d "$HOME/.catalyst" ]]; then

    read -r -n1 -p "Catalyst already installed. Reainstall it? [y/n]" REINSTALL
    echo -e "\n"

    if [[ $REINSTALL == "y" ]]; then
        info "Reinstalling"
        rm -rf ~/.catalyst
    else
        error "Exiting"
        exit 0
    fi

fi

mkdir -p ~/.catalyst/bin

info "Checking system"

cpu_arch=$(uname -m)
if [[ $cpu_arch == "x86_64" ]]; then
    cpu_arch="amd64"
elif [[ $cpu_arch == "aarch64" ]]; then
    cpu_arch="arm64"
fi

info "Downloading and Installing Catalyst"

touch ~/.catalyst/bin/catalyst

wget -q https://github.com/tunafysh/Catalyst/releases/latest/download/catalyst-linux-${cpu_arch}.zip | unzip -d ~/.catalyst/bin/catalyst

rm ~/.catalyst/bin/catalyst

info "Setting up Catalyst"

sudo sh -c export PATH=/home/$USER/.catalyst/bin:$PATH

echo -e "[Desktop Entry]\nName=Catalyst URL Handler\n
Exec=$HOME/.catalyst/bin/clyhandler %u\n
Type=Application\nTerminal=true\n
MimeType=x-scheme-handler/cly;" > $HOME/.local/share/applications/Catalyst.desktop

xdg-mime default $HOME/.local/share/applications/Catalyst.desktop x-scheme-handler/cly

echo -e "\e[1;92mCatalyst installed successfully\033[0m "
exit 0